title: "Project directory"
author: "Chris Vogt"
twitter: "C1V0"
description: "Portfolio of personal projects made with PHP, CakePHP, Jekyll, Wordpress, and more."
banner: "https://cdn.jsdelivr.net/gh/chrisvogt/projects@master/img/og-banner.png"
logo: "https://cdn.jsdelivr.net/gh/chrisvogt/chrisvogt.me@master/img/favicon-152.png"
analytics: "UA-33558417-8"
exclude:
  - README.md
